apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    group: web
type: Opaque
data:
  db-connection: {{ .Values.app.db.connection | b64enc | quote }}
  db-host: {{ .Values.app.db.host | b64enc | quote }}
  db-port: {{ .Values.app.db.port | toString | b64enc | quote }}
  db-name: {{ .Values.app.db.database | b64enc | quote }}
  db-password: {{ .Values.app.db.pass | b64enc | quote }}
  db-user: {{ .Values.app.db.user | b64enc | quote }}
